name: "Build Extension"
description: "Shared build steps for the extension"

inputs:
  run-checks:
    description: "Run typecheck and lint before building"
    required: false
    default: "false"

outputs:
  version:
    description: "Generated version string"
    value: ${{ steps.version.outputs.VERSION }}

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Generate version
      id: version
      shell: bash
      run: |
        YEAR=$(date -u +'%Y')
        MONTH=$(date -u +'%-m')
        DAY=$(date -u +'%-d')
        HOUR=$(date -u +'%-H')
        MINUTE=$(date -u +'%-M')
        MINUTE_OF_DAY=$((HOUR * 60 + MINUTE))
        VERSION="${YEAR}.${MONTH}.${DAY}.${MINUTE_OF_DAY}"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Generated version: $VERSION"

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Typecheck
      if: inputs.run-checks == 'true'
      shell: bash
      run: bun run typecheck

    - name: Lint
      if: inputs.run-checks == 'true'
      shell: bash
      run: bun run lint

    - name: Build
      shell: bash
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: bun run build

    - name: Package
      shell: bash
      run: |
        bun run chrome:pack
        bun run firefox:pack

    - name: Package source for Firefox review
      shell: bash
      run: ./package-source.sh

    - name: Generate update manifest
      shell: bash
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: bun run scripts/generate-update-manifest.ts
